#+title: NFTAMM

* Overview
NFTAMM is a system that allows people to fungitize their NFTs with redeemable tokens, and trade these redeemables in an AMM.

This allows for an easily determinable floor for people to use.

* Architecture
NFTAMM contains two contracts, the *Exhibition* and *Bazaar* contracts.
** Exhibition
Exhibition is vault system that allows NFT owners to deposit their NFTs into an exhibit (an account that relates to a single collection).

Every time a user deposits their NFT, they get a voucher token they can then trade for SOL in the Bazaar

** Bazaar
Bazaar is a market factory that instantiates a trading stand (a trading pool) for an exhibit's voucher tokens, and WSOL.

The Bazaar has 3 functions, Swap, Deposit Liquidity, and Withdraw Liquidity for users to interact with the stand, and an Instantiate Stand function for the exhibit creator to start a market for their collection


* Deploy script
the test folder has a full workflow of interacting with the exhibition and bazaar contracts

the deploy/testnet.ts is a script adapting features from the test files to start a new local-test-validator with the relavent data for easy network bootstrapping
