#+title: NFTAMM
* Overview
NFTAMM is a system that allows people to fungitize their NFTs, and trade these voucherables in an AMM.

This allows for an easily determinable floor for people to use.
* Architecture
*** Exhibition
Exhibition is vault system that allows NFT owners to deposit their NFTs into an exhibit (an account that relates to a single collection).

Every time a user deposits their NFT, they get a voucher token they can then trade for SOL in the Carnival
*** Shop
Shop is a AMM contract a trading stand (a trading pool) for an exhibit's voucher tokens, and WSOL.

The Shop has 3 functions, Swap, Deposit Liquidity, and Withdraw Liquidity for users to interact with the stand, and an Instantiate Stand function for the exhibit creator to start a market for their collection
*** Checkout
The next stage of the project was to implement a floor bid system, where bidders can place limit buy orders, and sellers can instant sell into these bids.

This involved storing using commited SOL for buy orders in a heap data structure, allowing functionallity for a seller to come market sell to a buyer, and the buyer being able to come redeem their newly acquired nft.

Checkout thus manages a heap to store user bids, and a DLL to store fulfilled orders
*** Carnival
Carnival is a an aggregator of mulitple amms for a single collection, the idea heavily inspired by Sudoswap
