#+title: PaperHand
* Overview
Paperhand is a suite of NFTAMM implementatios.

The core of paperhand allows nfts to be algorithimically associated with a collection, allowing for trading of NFTs through traditional AMMs, an instantaneous FloorBid, and through an aggregation of user-created pools (a structure heavily inspired by Sudoswap)
* Architecture
*** Exhibition
Exhibition is a Collection identification system. It creates PDAs hashed from the verified creators of a nft, and associates all other NFTs with the same identification system as the same collection.

In the future, the collection identification can happen through (Hyperspace way, and one other way)

expand exhibition to be ultimate filtering contract, make subset filtering, solving many-to-some-to-one problem

Exhibition also ties in a vault accounting system that allows users to deposit NFTs of the same collection, and receive a "voucher" token back (each representing an NFT)
*** Shop
Shop is a AMM contract a trading stand (a trading pool) for an exhibit's voucher tokens, and WSOL.

The Shop has 3 functions, Swap, Deposit Liquidity, and Withdraw Liquidity for users to interact with the stand, and an Instantiate Stand function for the exhibit creator to start a market for their collection
*** Checkout
The next stage of the project was to implement a floor bid system, where bidders can place limit buy orders, and sellers can instant sell into these bids.

This involved storing using commited SOL for buy orders in a heap data structure, allowing functionallity for a seller to come market sell to a buyer, and the buyer being able to come redeem their newly acquired nft.

Checkout thus manages a heap to store user bids, and a DLL to store fulfilled orders
*** Carnival
Carnival is a an aggregator of mulitple amms for a single collection, the idea heavily inspired by Sudoswap
* Next steps
** each card resolt reset user select nfts
** Trait gating pools
*** Design
create process for people to create shacks of what types of nfts can be sold
allow people to vote on tranches
*** have a creator defind groupping list, that allows people to bid for specific type of nfts
this is important since people want to idenity iwith a group, but some times there is too much confusion about what subgroup within in the commuity they want to identiy wiht. With a simple way for creators to be define their visuion for the collection, users can also quickly idenity with a group

update contracts and code
- add update authority as seeds
- review code
- sign all transactions multiple nfts
- proper fee stuff

THEN START TRYING TO DEPLOY
mainnet deploy
- vercel
- launch dog collection
- launch on mainnet




finsih all booth page functionality

add in functions in frontned
view button funcitonality
- redo page functionality and nagivating fuck
- add in router push stuff

- withdraw nft
- withdraw sol

- depo nft
- depo sol

- withdraw all


functionality
- don't see a collection? create your own unverifed collection
  - store nft selected image as default collection image
- search collection
- edit pricing
- contract fucntion to edit pricing

new pages
- verified and unverifed collection pages
  - top 20 verified magic collections

- new big hero page like sudo/magic

- your nft profile page
- your pool nft profile page

- activity page

bugs
- nft price gets stuck when selecting all nfts from a single pool
