#+title: PaperHand
* Overview
Paperhand is a suite of NFTAMM implementatios.

The core of paperhand allows nfts to be algorithimically associated with a collection, allowing for trading of NFTs through traditional AMMs, an instantaneous FloorBid, and through an aggregation of user-created pools (a structure heavily inspired by Sudoswap)

* Architecture
*** Exhibition
Exhibition is a Collection identification system. It creates PDAs hashed from the verified creators of a nft, and associates all other NFTs with the same identification system as the same collection.

In the future, the collection identification can happen through (Hyperspace way, and one other way)

 expand exhibition to be ultimate filtering contract, make subset filtering, solving many-to-some-to-one problem

Exhibition also ties in a vault accounting system that allows users to deposit NFTs of the same collection, and receive a "voucher" token back (each representing an NFT)
*** Shop

Shop is a AMM contract a trading stand (a trading pool) for an exhibit's voucher tokens, and WSOL.

The Shop has 3 functions, Swap, Deposit Liquidity, and Withdraw Liquidity for users to interact with the stand, and an Instantiate Stand function for the exhibit creator to start a market for their collection
*** Checkout
The next stage of the project was to implement a floor bid system, where bidders can place limit buy orders, and sellers can instant sell into these bids.

This involved storing using commited SOL for buy orders in a heap data structure, allowing functionallity for a seller to come market sell to a buyer, and the buyer being able to come redeem their newly acquired nft.

Checkout thus manages a heap to store user bids, and a DLL to store fulfilled orders
*** Carnival
Carnival is a an aggregator of mulitple amms for a single collection, the idea heavily inspired by Sudoswap

** Future work
*** bid on certain features
**** market sell certain features
*** check token account pubkeys to see if they are owned properly by the user
